language: bash
dist: trusty
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
install:
- sudo apt-get update -qq
- sudo apt-get install -qq expect bats
script:
- test/shellcheck
- bats --tap test/suites
notifications:
  email:
    on_success: never
