language: bash
dist: trusty
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
    - bats
    # - expect
script:
- test/shellcheck
- bats --tap test/suites
notifications:
  email:
    on_success: never
