language: bash
dist: trusty
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
install:
- sudo apt-get update -qq
- sudo apt-get install -qq expect bats
- git clone https://github.com/sstephenson/bats.git
script:
- bats --tap test/suites
- shellcheck --shell=bash homeshick.sh bin/homeshick {,lib/,lib/commands/,test/,test/fixtures/}*.sh {completions/,test/}*.bash
notifications:
  email:
    on_success: never
